/* eslint-disable @typescript-eslint/no-explicit-any */
// Auto-generated by `npx convex dev` — this stub exists for IDE support before first run.
// It will be overwritten by Convex CLI.

import {
  MutationBuilder,
  QueryBuilder,
  ActionBuilder,
  InternalMutationBuilder,
  InternalQueryBuilder,
  InternalActionBuilder,
  GenericDataModel,
} from "convex/server";

export declare const mutation: MutationBuilder<any, "public">;
export declare const query: QueryBuilder<any, "public">;
export declare const action: ActionBuilder<any, "public">;
export declare const internalMutation: InternalMutationBuilder<any>;
export declare const internalQuery: InternalQueryBuilder<any>;
export declare const internalAction: InternalActionBuilder<any>;
